//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotariatProjetUTC503.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.client_dossier = new HashSet<client_dossier>();
            this.bien = new HashSet<bien>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string nomEtatCivil { get; set; }
        public string prenom { get; set; }
        public string prenoms { get; set; }
        public string rue { get; set; }
        public string cp { get; set; }
        public string ville { get; set; }
        public System.DateTime dateNaiss { get; set; }
        public string lieuxNaiss { get; set; }
        public string nationalite { get; set; }
        public string profession { get; set; }
        public string telPortable { get; set; }
        public string telFixe { get; set; }
        public string mail { get; set; }
        public int idAdFiscale { get; set; }
        public Nullable<System.DateTime> dateDC { get; set; }
        public string lieuxDC { get; set; }
    
        public virtual adFiscale adFiscale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_dossier> client_dossier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bien> bien { get; set; }
    }
}
