//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotariatProjetUTC503.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dossier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dossier()
        {
            this.client_dossier = new HashSet<client_dossier>();
            this.document = new HashSet<document>();
            this.typeActe = new HashSet<typeActe>();
            this.mail = new HashSet<mail>();
            this.mvtfont = new HashSet<mvtfont>();
        }
    
        public int id { get; set; }
        public System.DateTime dateCreation { get; set; }
        public Nullable<System.DateTime> dateButoireSigna { get; set; }
        public Nullable<System.DateTime> dateSigna { get; set; }
        public Nullable<System.DateTime> dateTransImpot { get; set; }
        public Nullable<System.DateTime> dateRetourImpot { get; set; }
        public int idNotaire { get; set; }
        public int idClaire { get; set; }
        public int idSecretaire { get; set; }
    
        public virtual claire claire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_dossier> client_dossier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> document { get; set; }
        public virtual notaire notaire { get; set; }
        public virtual secretaire secretaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<typeActe> typeActe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mail> mail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mvtfont> mvtfont { get; set; }
    }
}
